name: Push files to S3
run-name: "Push files to S3: ${{ github.actor }} 🚀"
on:
  push:
    branches:
    - master
    - 'f/*'
  pull_request:
    branches: [master]
jobs:
  Docker-Login:
        uses: supergoongaming/sharedWorkflows/.github/workflows/docker_login.yml@master
  Build-Linux:
    runs-on: ubuntu-latest
    needs: Docker-Login
    container:
      image: unityci/editor:ubuntu-2022.3.10f1-webgl-2.0.0
      # credentials:
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: s3Artifact
          path: test/
  Push-S3:
        uses: supergoongaming/sharedWorkflows/.github/workflows/push_to_s3.yml@master
        needs: Build-Linux

        secrets:
          IAM_SECRET: ${{ secrets.IAM_SECRET }}
        with:
          IAM_USER: ${{ vars.IAM_USER }}
          bucket_region: "us-east-1"
          bucket_name: "triple-triad-external-site"