name: Push files to S3
run-name: "Push files to S3: ${{ github.actor }} 🚀"
on:
  push:
    branches:
    - master
    - 'f/*'
  pull_request:
    branches: [master]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2022.3.10f1-webgl-2.0.0
      env:
        UNITY_SERIAL: ${{secrets.UNITY_SERIAL}}
        UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}
        UNITY_USERNAME: ${{vars.UNITY_USERNAME}}
        INDEX_TEXT: "This was built using Github actions! <br>Kevin Blanchard and team<br>This is a remake of Triple Triad from FF8, and was made in 2018!"
      credentials:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Unity WebGl
        run: unity-editor -quit -batchmode -projectPath $(pwd) -executeMethod EditorScripts.PerformBuild -serial $UNITY_SERIAL -username $UNITY_USERNAME -password $UNITY_PASSWORD -logFile /tmp/buildLog.txt
      - name: Show Build Log
        run: cat /tmp/buildLog.txt
      - name: Show index
        run: cat webgl/index.html
      - name: Print Index text
        run: echo $INDEX_TEXT
      - name: Add to Index.hml
        run: sed -i "/<body>/a $INDEX_TEXT" webgl/index.html
      - name: Show index after
        run: cat webgl/index.html
      - uses: actions/upload-artifact@v3
        with:
          name: s3Artifact
          path: webgl/
  Push-S3:
        uses: supergoongaming/sharedWorkflows/.github/workflows/push_to_s3.yml@master
        needs: Build-Linux
        secrets:
          IAM_SECRET: ${{ secrets.IAM_SECRET }}
        with:
          IAM_USER: ${{ vars.IAM_USER }}
          bucket_region: "us-east-1"
          bucket_name: "triple-triad-external-site"