name: Push files to S3
run-name: "Push files to S3: ${{ github.actor }} 🚀"
on:
  push:
    branches:
    - master
    - 'f/*'
  pull_request:
    branches: [master]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: s3Artifact
          path: test/
  Push-S3:
        uses: supergoongaming/sharedWorkflows/.github/workflows/push_to_s3.yml@master
        needs: Build-Linux

        secrets:
          IAM_USER: ${{ vars.IAM_USER }}
          IAM_SECRET: ${{ secrets.IAM_SECRET }}
        with:
          bucket_region: "us-east-1"
          bucket_name: "triple-triad-external-site"